spring.application.name=netlikes

spring.datasource.url=jdbc:postgresql://localhost:5432/netlikes
spring.datasource.username=netlikes_user
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

